### ISSUE TITLE
Problem with autologon after restart

### ISSUE THREAD

**Issue by HarryPioter** [tbwfdu/mover#1]
Hello. 
Sorry for my english. 
And i don't exactly how to contact but i just wanna say we tester this app on Dell latitude 7450 with new  windows 10 installation 
And no matter what we do after komputer restarts never login to Admin account 
Yes password change but autologon not work i have try about 10 times only today

**Comment by tbwfdu** [comment]
Hi,

I have made some updates to Mover over the last couple of weeks. You can try with the latest release:

https://github.com/tbwfdu/mover/releases/tag/v1.4

I am not sure of your issue however I would check that the built-in Administrator account hasn't been renamed and that the setting "User cannot change password" is not enabled.

If it does not auto-login after running mover_install.exe **as an administrator or by right clicking on the file and selecting run as Administrator** log in with another account with local admin rights, and check that the files have been created in C:\Recovery\OEM\Mover. If this folder doesn't exist, and/or has no files in it, there must be a permission issue with the account you are running mover_install.exe as.

**Comment by HarryPioter** [comment]
Hello. 
I tested all posibilities and 
1. Problem was in our prepare komputer to the end user. We use autologon 4 times on admin account and after Windows made registry changes. I have exactly what vaules Windows change. 
2. We have nów another problem and this is a cis problem. But here we turn off one by one this settings
